### ISSUE TITLE
Epic: Sidebar View MVP

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/vscode-noir#10]
As a Noir developer, I want to prove and verify my Noir program with custom inputs through a GUI, so I can develop Noir programs in a terminal-less environment and free myself from learning Nargo.

```[tasklist]
- [ ] https://github.com/noir-lang/vscode-noir/issues/6
- [ ] https://github.com/noir-lang/vscode-noir/issues/7
- [ ] https://github.com/noir-lang/vscode-noir/issues/8
- [ ] https://github.com/noir-lang/vscode-noir/issues/9
```

## Open questions

1. Is compiling in the browser a blocker to this (particularly the proving & verifying steps)?

2. Is there a better alternative to how a GUI could be presented for developers to interact with their Noir programs? Definitely open to suggestions.
