### ISSUE TITLE
Epic: VS Code for the Web MVP

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/vscode-noir#38]
A minimal set of high impact DevEx improvements the VS Code extension could bring.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/vscode-noir/issues/37
- [ ] https://github.com/noir-lang/vscode-noir/issues/10
- [ ] https://github.com/noir-lang/vscode-noir/issues/33
```

**Comment by Savio-Sou** [comment]
Would assign `P-MEDIUM` to this issue (if _vscode-noir_ is monorepo'd into _noir_), as this could greatly improve UX for quick development, codebase review and learning Noir.

**Comment by Savio-Sou** [comment]
Closing as we can and already have examples on how to support GitHub Codespaces.
